insert into student (student_id,name,age,std) values (1,'Test1',5,1)
insert into student (student_id,name,age,std) values (5,'Test2',5,1)
insert into student (student_id,name,age,std) values (6,'Test3',5,1)
insert into student (student_id,name,age,std) values (2,'Test2',6,1)
insert into student (student_id,name,age,std) values (3,'Test3',7,1)
insert into student (student_id,name,age,std) values (4,'Test4',8,1)